import requests
from bs4 import BeautifulSoup
liens_pages_officiels=['http://www.creperie-saintgeorges.com',
'http://www.lafontaineauxperles.com',
'http://couleurscafe.com',
'http://www.lambassade-rennes.fr',
'http://www.restaurant-lareserve-rennes.fr',
'https://creperielagavotte-rennes.fr',
'http://www.legalopin.fr',
'http://www.lesarmentdevigne.com',
'http://restaurant-lesaintsauveur.fr',
'https://www.restaurantlatabledhippolyte.com',
'http://www.lebaronrouge.fr',
'http://www.restaurant-backtothe60s.com',
'http://www.cafe-breton.fr',
'http://www.lemoon-restaurant.com',
'http://portesmordelaises.fr',
'http://www.auberge-du-pont-dacigne.com',
'http://lachope.fr',
'http://www.cafenoir-rennes.com',
'http://www.lesablier.fr',
'http://www.creperie-moulerie.com',
'http://wok-forever.com',
'http://www.le-saison.com',
'http://creperie.placedelagare.fr/index.php/fr',
'http://latablevasselot.fr',
'http://www.tirebouchon.bzh',
'http://il-toscano.com',
'http://www.creperie-saintgeorges.com',
'http://www.lafontaineauxperles.com',
'http://couleurscafe.com',
'http://www.lambassade-rennes.fr',
'http://www.restaurant-lareserve-rennes.fr',
'http://www.legalopin.fr',
'http://www.lesarmentdevigne.com',
'http://restaurant-lesaintsauveur.fr',
'https://www.restaurantlatabledhippolyte.com',
'http://www.lebaronrouge.fr',
'http://www.restaurant-backtothe60s.com',
'http://www.cafe-breton.fr',
'http://www.lemoon-restaurant.com',
'http://portesmordelaises.fr',
'http://www.auberge-du-pont-dacigne.com',
'http://lachope.fr',
'http://www.cafenoir-rennes.com',
'http://www.lesablier.fr',
'http://www.creperie-moulerie.com',
'http://wok-forever.com',
'http://www.le-saison.com',
'http://creperie.placedelagare.fr/index.php/fr',
'http://latablevasselot.fr',
'http://www.tirebouchon.bzh',
'http://il-toscano.com',
'http://www.creperie-saintgeorges.com',
'http://www.lafontaineauxperles.com',
'http://couleurscafe.com',
'http://www.lambassade-rennes.fr',
'http://www.restaurant-lareserve-rennes.fr',
'https://creperielagavotte-rennes.fr',
'http://www.legalopin.fr',
'http://www.lesarmentdevigne.com',
'http://restaurant-lesaintsauveur.fr',
'https://www.restaurantlatabledhippolyte.com',
'http://www.lebaronrouge.fr',
'http://www.restaurant-backtothe60s.com',
'http://www.cafe-breton.fr',
'http://www.lemoon-restaurant.com',
'http://portesmordelaises.fr',
'http://www.auberge-du-pont-dacigne.com',
'http://www.cafenoir-rennes.com',
'http://www.lesablier.fr',
'http://www.creperie-moulerie.com',
'http://wok-forever.com',
'http://www.le-saison.com',
'http://creperie.placedelagare.fr/index.php/fr',
'http://latablevasselot.fr',
'http://www.tirebouchon.bzh',
'http://il-toscano.com',
'http://www.creperie-saintgeorges.com',
'http://www.lafontaineauxperles.com',
'http://couleurscafe.com',
'http://www.lambassade-rennes.fr',
'http://www.restaurant-lareserve-rennes.fr',
'https://creperielagavotte-rennes.fr',
'http://www.legalopin.fr',
'http://www.lesarmentdevigne.com',
'http://restaurant-lesaintsauveur.fr',
'https://www.restaurantlatabledhippolyte.com',
'http://www.lebaronrouge.fr',
'http://www.restaurant-backtothe60s.com',
'http://www.cafe-breton.fr',
'http://www.lemoon-restaurant.com',
'http://portesmordelaises.fr',
'http://www.auberge-du-pont-dacigne.com',
'http://www.cafenoir-rennes.com',
'http://www.lesablier.fr',
'http://www.creperie-moulerie.com',
'http://wok-forever.com',
'http://www.le-saison.com',
'http://creperie.placedelagare.fr/index.php/fr',
'http://latablevasselot.fr',
'http://www.tirebouchon.bzh',
'http://il-toscano.com',
'http://www.creperie-saintgeorges.com',
'http://www.lafontaineauxperles.com',
'http://couleurscafe.com',
'http://www.lambassade-rennes.fr',
'https://creperielagavotte-rennes.fr',
'http://www.legalopin.fr',
'http://www.lesarmentdevigne.com',
'http://restaurant-lesaintsauveur.fr',
'https://www.restaurantlatabledhippolyte.com',
'http://www.lebaronrouge.fr',
'http://www.restaurant-backtothe60s.com',
'http://www.cafe-breton.fr',
'http://www.lemoon-restaurant.com',
'http://portesmordelaises.fr',
'http://www.auberge-du-pont-dacigne.com',
'http://lachope.fr',
'http://www.cafenoir-rennes.com',
'http://www.lesablier.fr',
'http://www.creperie-moulerie.com',
'http://wok-forever.com',
'http://www.le-saison.com',
'http://creperie.placedelagare.fr/index.php/fr',
'http://latablevasselot.fr',
'http://www.tirebouchon.bzh',
'http://il-toscano.com',
'http://www.creperie-saintgeorges.com',
'http://www.lafontaineauxperles.com',
'http://couleurscafe.com',
'http://www.lambassade-rennes.fr',
'http://www.restaurant-lareserve-rennes.fr',
'https://creperielagavotte-rennes.fr',
'http://www.legalopin.fr',
'http://www.lesarmentdevigne.com',
'http://restaurant-lesaintsauveur.fr',
'https://www.restaurantlatabledhippolyte.com',
'http://www.lebaronrouge.fr',
'http://www.restaurant-backtothe60s.com',
'http://www.cafe-breton.fr',
'http://www.lemoon-restaurant.com',
'http://portesmordelaises.fr',
'http://www.auberge-du-pont-dacigne.com',
'http://lachope.fr',
'http://www.cafenoir-rennes.com',
'http://www.lesablier.fr',
'http://www.creperie-moulerie.com',
'http://wok-forever.com',
'http://www.le-saison.com',
'http://creperie.placedelagare.fr/index.php/fr',
'http://latablevasselot.fr',
'http://www.tirebouchon.bzh',
'http://il-toscano.com',] 
#gestion des exceptions: si la requête ne fonctionne pas (la page n'existe peut-être plus ou ne marche plus) --> requests.exceptions.SSLError erreur de certificat SSL
def detection_echec_requete(x):  
    try:
        requests.get(x)
    except requests.exceptions.SSLError as err:
        return('SSL')
    except requests.exceptions.HTTPError as err:
        return('HTTP')
    except requests.exceptions.ConnectionError as err:
        return('Connection')
def gestion_exception_echec_requete(x):  
    try:
        return requests.get(x)
    except requests.exceptions.SSLError as err:
        pass
    except requests.exceptions.HTTPError as err:
        pass
    except requests.exceptions.ConnectionError as err:
        pass
#on ne garde que les requêtes ayant le staut <Response [200]> if resp.status_code == 200:
#je pense que cette ligne fonctionne parce qu'on a <Response [200]> dès la première requête
requests_officiel_restau=[gestion_exception_echec_requete(lien) for lien in liens_pages_officiels if gestion_exception_echec_requete(lien)]
#accès au lien vers carte/menus de la page du site 
soups_officiel_restau = [BeautifulSoup(page.text, "html.parser") for page in requests_officiel_restau]
#recuperons tous les liens pouvant amener à un menu ou une carte
recup_liens_menus=[link.get('href') for link in soups_officiel_restau[0].findAll('a') if ('menu' in link.get('href')) or ('carte' in link.get('href'))] 
#prenons le premier résultat qui nous ai donné
#lien_page_menu=recup_lien_menu[0]

print(recup_liens_menus)