INSERT INTO ensaeats.restaurant(id_restaurant, nom) VALUES
(39785868, 'La Saint Georges'),
(24141567, 'Parc du Thabor'),
(90072796, 'La Fontaine aux Perles'),
(9883186, 'Crêperie Ouzh-Taol'),
(15495041, 'Le Fuji'),
(32383864, 'Falafel'),
(46443305, 'La Gavotte'),
(89270315, 'La Réserve'),
(11856744, 'Crêperie La Pommeraie'),
(81294756, 'Le Bistrot du Quai'),
(24175525, 'Couleurs Café'),
(85684488, "L'Ambassade"),
(63006783, 'Le Café des Bains'),
(98569741, 'Le Bocal'),
(84663294, "L'Atelier des Gourmets"),
(43363040, "O'Connells"),
(47763275, 'Le Pagnol'),
(75119756, 'Crêperie Sainte-Anne'),
(43524094, "L'Artiste Assoiffé"),
(75115434, 'Ar Pillig'),
;
INSERT INTO ensaeats.avis(id_avis,avis,id_restaurant) VALUES
(200, "One of the best creperies in Rennes, and it's very upscale compared to your tradition crepe place. Of course, that means the prices are upscale too. But the...", 39785868),
(201, 'The headline for my review of La Saint George is "This is a super place for fancy crepes!".  I am cleaning up some review drafts I started before COVID hit....', 39785868),
(202, 'The name comes up often when asking locals about the best crêperie in Rennes. To be honest, the place is a little too trendy-looking for me. Lots of velvet...', 39785868),
(203, "One of the best creperies in Rennes, and it's very upscale compared to your tradition crepe place. Of course, that means the prices are upscale too. But the...", 24141567),
(204, 'The headline for my review of La Saint George is "This is a super place for fancy crepes!".  I am cleaning up some review drafts I started before COVID hit....', 24141567),
(205, 'The name comes up often when asking locals about the best crêperie in Rennes. To be honest, the place is a little too trendy-looking for me. Lots of velvet...', 24141567),
(206, "One of the best creperies in Rennes, and it's very upscale compared to your tradition crepe place. Of course, that means the prices are upscale too. But the...", 9883186),
(207, 'The headline for my review of La Saint George is "This is a super place for fancy crepes!".  I am cleaning up some review drafts I started before COVID hit....', 9883186),
(208, 'The name comes up often when asking locals about the best crêperie in Rennes. To be honest, the place is a little too trendy-looking for me. Lots of velvet...', 9883186),
(209, "One of the best creperies in Rennes, and it's very upscale compared to your tradition crepe place. Of course, that means the prices are upscale too. But the...", 46443305),
(210, 'The headline for my review of La Saint George is "This is a super place for fancy crepes!".  I am cleaning up some review drafts I started before COVID hit....', 46443305),
(211, 'The name comes up often when asking locals about the best crêperie in Rennes. To be honest, the place is a little too trendy-looking for me. Lots of velvet...', 46443305),
(212, "One of the best creperies in Rennes, and it's very upscale compared to your tradition crepe place. Of course, that means the prices are upscale too. But the...", 85684488),
(213, 'The headline for my review of La Saint George is "This is a super place for fancy crepes!".  I am cleaning up some review drafts I started before COVID hit....', 85684488),
(214, 'The name comes up often when asking locals about the best crêperie in Rennes. To be honest, the place is a little too trendy-looking for me. Lots of velvet...', 85684488),
(215, "One of the best creperies in Rennes, and it's very upscale compared to your tradition crepe place. Of course, that means the prices are upscale too. But the...", 98569741),
(216, 'The headline for my review of La Saint George is "This is a super place for fancy crepes!".  I am cleaning up some review drafts I started before COVID hit....', 98569741),
(217, 'The name comes up often when asking locals about the best crêperie in Rennes. To be honest, the place is a little too trendy-looking for me. Lots of velvet...', 98569741),
(218, "One of the best creperies in Rennes, and it's very upscale compared to your tradition crepe place. Of course, that means the prices are upscale too. But the...", 43363040),
(219, 'The headline for my review of La Saint George is "This is a super place for fancy crepes!".  I am cleaning up some review drafts I started before COVID hit....', 43363040),
(220, 'The name comes up often when asking locals about the best crêperie in Rennes. To be honest, the place is a little too trendy-looking for me. Lots of velvet...', 43363040),
(221, "One of the best creperies in Rennes, and it's very upscale compared to your tradition crepe place. Of course, that means the prices are upscale too. But the...", 75119756),
(222, 'The headline for my review of La Saint George is "This is a super place for fancy crepes!".  I am cleaning up some review drafts I started before COVID hit....', 75119756),
(223, 'The name comes up often when asking locals about the best crêperie in Rennes. To be honest, the place is a little too trendy-looking for me. Lots of velvet...', 75119756),
(224, "One of the best creperies in Rennes, and it's very upscale compared to your tradition crepe place. Of course, that means the prices are upscale too. But the...", 75115434),
(225, 'The headline for my review of La Saint George is "This is a super place for fancy crepes!".  I am cleaning up some review drafts I started before COVID hit....', 75115434),
(226, 'The name comes up often when asking locals about the best crêperie in Rennes. To be honest, the place is a little too trendy-looking for me. Lots of velvet...', 75115434),
;