postgresql:
  image:
    tag: "14"
    pullPolicy: IfNotPresent
  global:
    postgresql:
      service: 
        ports:
          postgresql: 5432
  auth:
    postgresPassword: "user"
    username: "user"
    password: "user"
    database: "user"
  extensions:
    postgis: false
# primary:
  #  initdb:
  #   scriptsConfigMap: ./script_bdd/script_sql_bdd.sql
  
discoverable:
  allow: true

security:
  networkPolicy: 
    enabled: true