postgresql:
  image:
    tag: "14"
    pullPolicy: IfNotPresent
  global:
    postgresql:
      service: 
        ports:
          postgresql: 5432
  auth:
    postgresPassword: changeme
    username: changeme
    password: changeme
    database: changeme
 
# primary:
#      initdb:
#      scriptsConfigMap: ./script_bdd/script_sql_bdd.sql

security:
  networkPolicy: 
    enabled: true
