postgresql:
  image:
    tag: "14"
    pullPolicy: IfNotPresent
  global:
    postgresql:
      service: 
        ports:
          postgresql: 5432
  auth:
    postgresPassword: eyerys
    username: user
    password: eyerys
    database: bdd
 
# primary:
#      initdb:
#      scriptsConfigMap: ./script_bdd/script_sql_bdd.sql

security:
  networkPolicy: 
    enabled: true
