apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas : 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: aiflowzone/ensaeats:05.07.2022
        imagePullPolicy: Always #effet de cache
        envFrom: 
        - secretRef:
            name: secret-postgres-bitnami
        
# apiVersion: v1
# kind: Secret
# metadata:
#   name: secret-postgres-bitnami
# type: Opaque
# stringData:
#   password: ****
#   postgres-password: ****
#   replication-password: ****
#   DB_HOST: bdd-postgresql
#   DB_PORT: "5432"
#   DATABASE: ensaeats
#   USER: user
     
